from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from datetime import datetime
import os

console = Console()


def show_target_info(target_info):

    table = Table(title="\nTarget Information")

    table.add_column("Field", style="cyan", no_wrap=True)
    table.add_column("Value", style="green")

    table.add_row("Original Input", target_info["original"])
    table.add_row("Hostname", target_info["hostname"])
    table.add_row("IP Address", target_info["ip"])
    table.add_row("Scheme", target_info["scheme"])

    console.print(table)


def show_dns_records(dns_records):

    table = Table(title="\nDNS Records")

    table.add_column("Record Type", style="cyan", no_wrap=True)
    table.add_column("Value", style="green")

    for record_type, values in dns_records.items():

        if values:
            for value in values:
                table.add_row(record_type, value)
        else:
            table.add_row(record_type, "[red]No records found[/red]")

    console.print(table)

def show_whois_info(whois_info):

    table = Table(title="\nWHOIS Information")

    table.add_column("Field", style="cyan", no_wrap=True)
    table.add_column("Value", style="green")

    for key, value in whois_info.items():

        if isinstance(value, list):
            value = "\n".join(str(v) for v in value)

        table.add_row(str(key), str(value))

    console.print(table)

def show_nmap_results(scan_results):

    table = Table(title="\nNmap Scan Results")

    table.add_column("Port", style="cyan", no_wrap=True)
    table.add_column("State", style="green")
    table.add_column("Service", style="yellow")
    table.add_column("Version", style="magenta")

    if not scan_results:
        console.print("[red]No scan results available.[/red]")
        return

    for port, info in scan_results.items():

        table.add_row(
            port,
            info["state"],
            info["service"],
            info["version"]
        )

    console.print(table)

def save_report(target, dns_records, whois_info, nmap_results):

    os.makedirs("reports", exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    filename = f"reports/{target.hostname}_{timestamp}.txt"

    with open(filename, "w") as report:

        report.write("=" * 60 + "\n")
        report.write("ReconX Scan Report\n")
        report.write("=" * 60 + "\n\n")

        report.write(f"Scan Time : {datetime.now()}\n")
        report.write(f"Target    : {target.original_input}\n")
        report.write(f"Hostname  : {target.hostname}\n")
        report.write(f"IP        : {target.ip}\n")
        report.write(f"Scheme    : {target.scheme}\n\n")

        report.write("=" * 60 + "\n")
        report.write("DNS RECORDS\n")
        report.write("=" * 60 + "\n")

        for record_type, values in dns_records.items():

            report.write(f"\n{record_type}:\n")

            if values:
                for value in values:
                    report.write(f"  - {value}\n")
            else:
                report.write("  No records found\n")

        report.write("\n")
        report.write("=" * 60 + "\n")
        report.write("WHOIS INFORMATION\n")
        report.write("=" * 60 + "\n")

        for key, value in whois_info.items():

            if isinstance(value, list):
                value = ", ".join(str(v) for v in value)

            report.write(f"{key}: {value}\n")

        report.write("\n")
        report.write("=" * 60 + "\n")
        report.write("NMAP RESULTS\n")
        report.write("=" * 60 + "\n")

        for port, info in nmap_results.items():

            report.write(
                f"{port} | "
                f"{info['state']} | "
                f"{info['service']} | "
                f"{info['version']}\n"
            )

        report.write("\n")
        report.write("=" * 60 + "\n")
        report.write("Generated by ReconX\n")
        report.write("=" * 60 + "\n")

    return filename

def show_scan_summary(scan_time):

    summary = (
        "✓ Target Validation\n"
        "✓ DNS Lookup\n"
        "✓ WHOIS Lookup\n"
        "✓ Nmap Scan\n"
        "✓ Report Generation\n\n"
        f"Total Scan Time : {scan_time:.2f} seconds"
    )

    console.print(
        Panel(
            summary,
            title="[bold green]ReconX Scan Summary[/bold green]",
            border_style="green"
        )
    )